branch: master

pipelines:
  - pipeline1:
     - task1
     - task2
     - task3
  - pipeline2:
     - task4
  - pipeline3:
     - task1
     - task3

tasks:
  - task1:
      cmd: command
  - task2:
      cmd: command
  - task3:
      cmd: command
  - task4:
      cmd: command
  - task5:
      cmd: command
